services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_chat_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector

  embedding-service:
    build: ./embedding-service
    restart: always
    ports:
      - 8001:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db

volumes:
  pgdata: